name: PC Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  TZ: Asia/Shanghai

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
